-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 20:00:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sneakers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sneakers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sneakers` DEFAULT CHARACTER SET utf8 ;
USE `sneakers` ;

-- -----------------------------------------------------
-- Table `sneakers`.`tenis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sneakers`.`tenis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL,
  `preco` DECIMAL(10,2) NULL,
  `tamanho` ENUM("36", "37", "38", "39", "40", "41", "42") NULL,
  `img_src` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NULL,
  `qtd_estoque` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sneakers`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sneakers`.`clientes` (
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `bairro` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `num_logradouro` INT NULL,
  `telefone` VARCHAR(13) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sneakers`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sneakers`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM("entregue", "processando", "cancelado", "encaminhado") NULL,
  `pedidoscol` VARCHAR(45) NULL,
  `clientes_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_clientes_idx` (`clientes_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes`
    FOREIGN KEY (`clientes_cpf`)
    REFERENCES `sneakers`.`clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sneakers`.`tenis_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sneakers`.`tenis_pedido` (
  `tenis_id` INT NOT NULL,
  `pedidos_id` INT NOT NULL,
  `qtd_pedido` INT NULL,
  `data` VARCHAR(8) NULL,
  PRIMARY KEY (`tenis_id`, `pedidos_id`),
  INDEX `fk_tenis_has_pedidos_pedidos1_idx` (`pedidos_id` ASC) VISIBLE,
  INDEX `fk_tenis_has_pedidos_tenis1_idx` (`tenis_id` ASC) VISIBLE,
  CONSTRAINT `fk_tenis_has_pedidos_tenis1`
    FOREIGN KEY (`tenis_id`)
    REFERENCES `sneakers`.`tenis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tenis_has_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `sneakers`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
